name: ci
on: push

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: choco-win10-sdk
      run: |
        choco install windows-sdk-10.1 || type C:\ProgramData\chocolatey\logs\chocolatey.log
    - name: moreLog
      run: |
        type C:\Users\runneradmin\AppData\Local\Temp\chocolatey\windows-sdk-10.1_346b5cc2-a338-4916-927d-68483e6e4512.log

    - name: list env vars
      run: |
        SET

    - name: install boots
      shell: pwsh
      run: |
        dotnet tool install --global boots
        boots https://aka.ms/xamarin-android-commercial-d16-3-windows
    - name: Clone submodules
      run: |
        git submodule update --init --recursive
    - name: Build
      shell: pwsh
      run: |
        .\build.ps1
    - name: Package and upload
      run: |
        nuget.bat ${{ secrets.NUGET_API_KEY }}
